"""THIS IS THE INIT MODULE WHERE WE IMPORT THE FILES OF THE PROJECT"""

from UC3M_Care.VACCINE_REQUEST import VACCINE_REQUEST
from UC3M_Care.UC3M_VaccineManager import VACCINE_MANAGER
from UC3M_Care.VACCINE_MANAGEMENT_EXCEPTION import VACCINE_MANAGEMENT_EXCEPTION
