"""THIS IS THE INIT FUNCTION WHERE WE IMPORT THE FILES OF THE PROJECT"""

from UC3M_Care.VACCINE_REQUEST import VACCINE_REQUEST
from UC3M_Care.VACCINE_MANAGER import VACCINE_MANAGER
from UC3M_Care.VACCINE_MANAGEMENT_EXCEPTION import VACCINE_MANAGEMENT_EXCEPTION
