"""THIS IS THE INIT MODULE WHERE WE IMPORT THE FILES OF THE PROJECT"""

from UC3M_Care.UC3M_VACCINEREQUEST import VACCINEREQUEST
from UC3M_Care.VACCINE_MANAGER import VACCINE_MANAGER
from UC3M_Care.VACCINE_MANAGEMENT_EXCEPTION import VACCINE_MANAGEMENT_EXCEPTION
